version: '3'

services:
  nodeService:
    image: node:20-alpine
    container_name: node
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - 3000:3000
    command: >
      sh -c "
      npm install &&
      npm start
      "
    depends_on:
      - db
  
  db:
    image: mysql:8
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodeDB
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3606:3606"